version: '3.7'
services:
  redis:
    image: redis:latest
    command: redis-server --requirepass admin --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  redisinsight:
    image: redislabs/redisinsight:latest
    environment:
      - REDISINSIGHT_HOSTS=redis:6379
      - REDISINSIGHT_PASSWORD=admin
    ports:
      - 8001:8001
    depends_on:
      - redis

volumes:
  redis_data:

